title: Omotola Olufemi
logo: profile-image.jpeg
description: A data analyst with 3 years experience using excel for reporting, sql for data manipulation and power bi for visualization.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
