title: Omotola Olufemi
logo: image-new.jpeg
description: A data analyst with 2 years experience using Excel, SQL and Power BI to transform raw data into clear, actionable insights.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
